import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'

//
// is expected that the files
// are going to be re-proccesed
//

/** @type {esbuild.BuildOptions[]} */
const formats = [
  { format: 'cjs', outfile: 'lib/obsidian-fnc.js', target: 'ES2018' },
  { format: 'esm', outfile: 'lib/obsidian-fnc.mjs', target: 'ES2018' },
]

/** @type {esbuild.BuildOptions} */
const BASE_CONFIG = {
  entryPoints: ['src/index.ts'],
  bundle: true,
  treeShaking: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
    ...builtins,
  ],
}

/** @type {esbuild.BuildOptions} */
const DEV_CONFIG = {
  ...BASE_CONFIG,
  watch: true,
  sourcemap: 'inline',
  logLevel: 'info',
}

/** @type {esbuild.BuildOptions} */
const PROD_CONFIG = {
  ...BASE_CONFIG,
  watch: false,
  sourcemap: false,
  logLevel: 'error',
  banner: {
    js: [
      '/**',
      ' * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD',
      ' * if you want to view the source, please visit the github repository of this plugin',
      ' */',
    ].join('\n'),
  },
}

// compilation process
if ((process.env.npm_lifecycle_script || '').includes('production')) {
  for (const format of formats) {
    await esbuild.build({ ...PROD_CONFIG, ...format })
  }
} else {
  for (const format of formats) {
    await esbuild.build({ ...DEV_CONFIG, ...format })
  }
}
